---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tekatekocom/t.tekateko.com/
    - /bin/cp -R base $DEPLOYPATH
    - /bin/cp -R staticfiles $DEPLOYPATH
    - /bin/cp -R todo_list $DEPLOYPATH
    - /bin/cp db.sqlite3 $DEPLOYPATH
    - /bin/cp manage.py $DEPLOYPATH
    - /bin/cp Procfile $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp runtime.txt $DEPLOYPATH
    